### PR TITLE
update plugin to 2021.2

### PR DESCRIPTION
**Pull request by anstarovoyt**

### CODE REVIEW

**Comment by anstarovoyt** [comment]
@olance any updates?

**Comment by olance** [comment]
@anstarovoyt I'm very sorry for the delay, it's quite hard to keep up with the project along with my regular job.
I'll try to get better at it 🤞 

Thanks a lot for the PR, I'm planning on releasing this week-end.

**Comment by olance** [comment]
I actually can't merge this as is, need to double check the version conventions.

I basically have 3 version "branches" depending on which IDE versions are supported.
`1.0.3.201` is the `1.0.3` version for IDEs starting at version `201`, so your PR shouldn't touch the `201` part, only the patch part from `1.0.3` to `1.0.4` for instance. But that's something I'll update myself when releasing.

I think the only change in your PR should be:
```diff
- pluginUntilBuild = 212
+ pluginUntilBuild = 212.*
```

But again, I'll check this out this week-end!
Thanks again ✌️

**Comment by olance** [comment]
Closing as I just handled this in another commit!
Thanks again for the PR though :)

**Pull request closed without merging**
